@startuml
participant Administrator

Administrator -> UI: 1. sendIsbn
activate UI
UI -> AddCopyForm: 2. forwardIsbn
activate AddCopyForm
AddCopyForm -> SystemController: 3. addBookCopyByISBN
activate SystemController
SystemController -> DataAccessFacade: 4. readBooksMap
activate DataAccessFacade
deactivate DataAccessFacade
SystemController -> SystemController: 5. validateBookIsbn
activate SystemController
deactivate SystemController
SystemController -> SystemController: 6. addBookCopy
activate SystemController
deactivate SystemController
SystemController -> DataAccessFacade: 7. updateBook
activate DataAccessFacade
deactivate DataAccessFacade
deactivate SystemController
AddCopyForm -> AddCopyForm: 8. updateAccordingState
activate AddCopyForm
deactivate AddCopyForm
deactivate AddCopyForm
@enduml